### PR TITLE
46 remove register endpoint

### PR DESCRIPTION
**Pull request by olech2412**

### CODE REVIEW

**Comment by olech2412** [comment]
@whosFritz take a look at http://localhost:8083/mensaHub/swagger-ui/index.html for api doc

**Review by whosFritz — APPROVED** [review]
will definitely break in production but its friday noon so idc at all

**Comment by olech2412** [comment]
> will definitely break in production but its friday noon so idc at all

Why? 😂

**Comment by whosFritz** [comment]
> > will definitely break in production but its friday noon so idc at all
> 
> Why? 😂

Just saying 😂😂😂
i was joking

**Pull request merged**
